### PR TITLE
Update to 1.19.2

### PR DESCRIPTION
**Pull request by MeeniMc**
Nothing fancy, just upgrademappings and gradle update

### CODE REVIEW

**Comment by MeeniMc** [comment]
works with 1.18.2 with no changes.

**Comment by MeeniMc** [comment]
Required quite a bit of changes for 1.19

**Comment by linux-leo** [comment]
@MeeniMc It would be great if you could build the mod until the pull request gets merged

**Comment by MeeniMc** [comment]
Here you go: 
https://github.com/MeeniMc/continue-button/releases/tag/v1.0.5+1.19

**Comment by MeeniMc** [comment]
Broken with 1.19.3

**Comment by MeeniMc** [comment]
mod is abandonned

**Pull request closed without merging**
